/**
 * Knetik.io Data Collector REST API
 * <p>Use this API to send application data to Knetik.io including user/device information and transactional events.</p> <p>   Please consult the <a href=\"/doc\">official user documentation</a> to find out how to send data, and how this data is used. <p></p> <h2>Notes</h2> <br> New more ReSTful implementation of the telemetry data collection service. Legacy clients can still use the old API format, but we strongly recommend switching over to this new format. Navigate to the legacy documentation using the dropdown at the top of this page. <p></p> <h2>User IDs and Device IDs</h2> <br> Knetik.io can uniquely associate state, events and transactions to users and/or devices for your application. In order to accomplish this, each API call takes userId and deviceId as parameters in the request object. At least one of these must be provided in the request object, except as explicitly noted. <br> <p></p> <h2>Timestamps</h2> <br> All timestamp parameters must be epoch timestamps in milliseconds. <br> <p></p> <h2>Required Request Headers</h2> <br> The following HTTP header values must be provided for each API call: <ul>   <li>     <b>Content-Type: application/json</b>   </li> </ul> <p></p> <h2>Required Query Parameters</h2> <br> All API calls also require the following query parameters to be present on the URL: <ul>   <li>     <b>customer_id:</b> your unique customer ID   </li> </ul> <p></p> <h2>API Responses</h2> <br> If successful, API calls will simply return an HTTP response code of ACCEPTED (202) with no other data. If errors occur, a JSON payload will be returned containing detailed error information and an appropriate HTTP error status code will be provided (as documented in each of the API methods). <br> <p></p>
 *
 * OpenAPI spec version: 2.0
 * Contact: support@knetik.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonParseException;
import com.google.gson.reflect.TypeToken;
import java.lang.reflect.Type;
import java.util.List;
import java.util.Date;
import io.swagger.client.model.*;

public class JsonUtil {
  public static GsonBuilder gsonBuilder;

  static {
    gsonBuilder = new GsonBuilder();
    gsonBuilder.serializeNulls();
    gsonBuilder.setDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSSZ");
    gsonBuilder.registerTypeAdapter(Date.class, new JsonDeserializer<Date>() {
      public Date deserialize(JsonElement json, Type typeOfT, JsonDeserializationContext context) throws JsonParseException {
        return new Date(json.getAsJsonPrimitive().getAsLong());
      }
    });
  }

  public static Gson getGson() {
    return gsonBuilder.create();
  }

  public static String serialize(Object obj){
    return getGson().toJson(obj);
  }

  public static <T> T deserializeToList(String jsonString, Class cls){
    return getGson().fromJson(jsonString, getListTypeForDeserialization(cls));
  }

  public static <T> T deserializeToObject(String jsonString, Class cls){
    return getGson().fromJson(jsonString, getTypeForDeserialization(cls));
  }

  public static Type getListTypeForDeserialization(Class cls) {
    String className = cls.getSimpleName();
    
    if ("DataCollectorBaseRequest".equalsIgnoreCase(className)) {
      return new TypeToken<List<DataCollectorBaseRequest>>(){}.getType();
    }
    
    if ("DataCollectorBatchRequest".equalsIgnoreCase(className)) {
      return new TypeToken<List<DataCollectorBatchRequest>>(){}.getType();
    }
    
    if ("DataCollectorBeginTransactionRequest".equalsIgnoreCase(className)) {
      return new TypeToken<List<DataCollectorBeginTransactionRequest>>(){}.getType();
    }
    
    if ("DataCollectorEndTransactionRequest".equalsIgnoreCase(className)) {
      return new TypeToken<List<DataCollectorEndTransactionRequest>>(){}.getType();
    }
    
    if ("DataCollectorNewDeviceRequest".equalsIgnoreCase(className)) {
      return new TypeToken<List<DataCollectorNewDeviceRequest>>(){}.getType();
    }
    
    if ("DataCollectorNewUserRequest".equalsIgnoreCase(className)) {
      return new TypeToken<List<DataCollectorNewUserRequest>>(){}.getType();
    }
    
    if ("DataCollectorTuneRequest".equalsIgnoreCase(className)) {
      return new TypeToken<List<DataCollectorTuneRequest>>(){}.getType();
    }
    
    if ("DataCollectorUpdateCollectionRequest".equalsIgnoreCase(className)) {
      return new TypeToken<List<DataCollectorUpdateCollectionRequest>>(){}.getType();
    }
    
    if ("DataCollectorUpdateDeviceStateRequest".equalsIgnoreCase(className)) {
      return new TypeToken<List<DataCollectorUpdateDeviceStateRequest>>(){}.getType();
    }
    
    if ("DataCollectorUpdateTransactionRequest".equalsIgnoreCase(className)) {
      return new TypeToken<List<DataCollectorUpdateTransactionRequest>>(){}.getType();
    }
    
    if ("DataCollectorUpdateUserStateRequest".equalsIgnoreCase(className)) {
      return new TypeToken<List<DataCollectorUpdateUserStateRequest>>(){}.getType();
    }
    
    if ("NewEventRequest".equalsIgnoreCase(className)) {
      return new TypeToken<List<NewEventRequest>>(){}.getType();
    }
    
    return new TypeToken<List<Object>>(){}.getType();
  }

  public static Type getTypeForDeserialization(Class cls) {
    String className = cls.getSimpleName();
    
    if ("DataCollectorBaseRequest".equalsIgnoreCase(className)) {
      return new TypeToken<DataCollectorBaseRequest>(){}.getType();
    }
    
    if ("DataCollectorBatchRequest".equalsIgnoreCase(className)) {
      return new TypeToken<DataCollectorBatchRequest>(){}.getType();
    }
    
    if ("DataCollectorBeginTransactionRequest".equalsIgnoreCase(className)) {
      return new TypeToken<DataCollectorBeginTransactionRequest>(){}.getType();
    }
    
    if ("DataCollectorEndTransactionRequest".equalsIgnoreCase(className)) {
      return new TypeToken<DataCollectorEndTransactionRequest>(){}.getType();
    }
    
    if ("DataCollectorNewDeviceRequest".equalsIgnoreCase(className)) {
      return new TypeToken<DataCollectorNewDeviceRequest>(){}.getType();
    }
    
    if ("DataCollectorNewUserRequest".equalsIgnoreCase(className)) {
      return new TypeToken<DataCollectorNewUserRequest>(){}.getType();
    }
    
    if ("DataCollectorTuneRequest".equalsIgnoreCase(className)) {
      return new TypeToken<DataCollectorTuneRequest>(){}.getType();
    }
    
    if ("DataCollectorUpdateCollectionRequest".equalsIgnoreCase(className)) {
      return new TypeToken<DataCollectorUpdateCollectionRequest>(){}.getType();
    }
    
    if ("DataCollectorUpdateDeviceStateRequest".equalsIgnoreCase(className)) {
      return new TypeToken<DataCollectorUpdateDeviceStateRequest>(){}.getType();
    }
    
    if ("DataCollectorUpdateTransactionRequest".equalsIgnoreCase(className)) {
      return new TypeToken<DataCollectorUpdateTransactionRequest>(){}.getType();
    }
    
    if ("DataCollectorUpdateUserStateRequest".equalsIgnoreCase(className)) {
      return new TypeToken<DataCollectorUpdateUserStateRequest>(){}.getType();
    }
    
    if ("NewEventRequest".equalsIgnoreCase(className)) {
      return new TypeToken<NewEventRequest>(){}.getType();
    }
    
    return new TypeToken<Object>(){}.getType();
  }

};
