/**
 * Knetik.io Data Collector REST API
 * <p>Use this API to send application data to Knetik.io including user/device information and transactional events.</p> <p>   Please consult the <a href=\"/doc\">official user documentation</a> to find out how to send data, and how this data is used. <p></p> <h2>Notes</h2> <br> New more ReSTful implementation of the telemetry data collection service. Legacy clients can still use the old API format, but we strongly recommend switching over to this new format. Navigate to the legacy documentation using the dropdown at the top of this page. <p></p> <h2>User IDs and Device IDs</h2> <br> Knetik.io can uniquely associate state, events and transactions to users and/or devices for your application. In order to accomplish this, each API call takes userId and deviceId as parameters in the request object. At least one of these must be provided in the request object, except as explicitly noted. <br> <p></p> <h2>Timestamps</h2> <br> All timestamp parameters must be epoch timestamps in milliseconds. <br> <p></p> <h2>Required Request Headers</h2> <br> The following HTTP header values must be provided for each API call: <ul>   <li>     <b>Content-Type: application/json</b>   </li> </ul> <p></p> <h2>Required Query Parameters</h2> <br> All API calls also require the following query parameters to be present on the URL: <ul>   <li>     <b>customer_id:</b> your unique customer ID   </li> </ul> <p></p> <h2>API Responses</h2> <br> If successful, API calls will simply return an HTTP response code of ACCEPTED (202) with no other data. If errors occur, a JSON payload will be returned containing detailed error information and an appropriate HTTP error status code will be provided (as documented in each of the API methods). <br> <p></p>
 *
 * OpenAPI spec version: 2.0
 * Contact: support@knetik.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class DataCollectorUpdateCollectionRequest {
  
  @SerializedName("balance")
  private Double balance = null;
  @SerializedName("balance_modification")
  private Double balanceModification = null;
  @SerializedName("currency")
  private Boolean currency = null;
  @SerializedName("device_id")
  private String deviceId = null;
  @SerializedName("event_properties")
  private Object eventProperties = null;
  @SerializedName("event_timestamp")
  private Long eventTimestamp = null;
  @SerializedName("name")
  private String name = null;
  @SerializedName("request_type")
  private String requestType = null;
  @SerializedName("send_timestamp")
  private Long sendTimestamp = null;
  @SerializedName("user_id")
  private String userId = null;

  /**
   * Final balance after the transaction
   **/
  @ApiModelProperty(required = true, value = "Final balance after the transaction")
  public Double getBalance() {
    return balance;
  }
  public void setBalance(Double balance) {
    this.balance = balance;
  }

  /**
   * The amount changed (delta) in the transaction
   **/
  @ApiModelProperty(required = true, value = "The amount changed (delta) in the transaction")
  public Double getBalanceModification() {
    return balanceModification;
  }
  public void setBalanceModification(Double balanceModification) {
    this.balanceModification = balanceModification;
  }

  /**
   * Whether the unit being updated is a currency unit or not
   **/
  @ApiModelProperty(required = true, value = "Whether the unit being updated is a currency unit or not")
  public Boolean getCurrency() {
    return currency;
  }
  public void setCurrency(Boolean currency) {
    this.currency = currency;
  }

  /**
   * Unique ID of the device triggering the event
   **/
  @ApiModelProperty(value = "Unique ID of the device triggering the event")
  public String getDeviceId() {
    return deviceId;
  }
  public void setDeviceId(String deviceId) {
    this.deviceId = deviceId;
  }

  /**
   * A key/value list of properties for this event. Values can be numerical, strings or booleans, proper typing matters (quoted vs unquoted)
   **/
  @ApiModelProperty(value = "A key/value list of properties for this event. Values can be numerical, strings or booleans, proper typing matters (quoted vs unquoted)")
  public Object getEventProperties() {
    return eventProperties;
  }
  public void setEventProperties(Object eventProperties) {
    this.eventProperties = eventProperties;
  }

  /**
   * Epoch timestamp <i>in milliseconds</i> of when event itself occurred
   **/
  @ApiModelProperty(required = true, value = "Epoch timestamp <i>in milliseconds</i> of when event itself occurred")
  public Long getEventTimestamp() {
    return eventTimestamp;
  }
  public void setEventTimestamp(Long eventTimestamp) {
    this.eventTimestamp = eventTimestamp;
  }

  /**
   * Name of the unit/collection/currency being updated
   **/
  @ApiModelProperty(required = true, value = "Name of the unit/collection/currency being updated")
  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
  }

  /**
   * Specifies the canonical model name of the request. Ex: DataCollectorNewUserRequest -> newUser, NewEventRequest -> newEvent,e tc
   **/
  @ApiModelProperty(required = true, value = "Specifies the canonical model name of the request. Ex: DataCollectorNewUserRequest -> newUser, NewEventRequest -> newEvent,e tc")
  public String getRequestType() {
    return requestType;
  }
  public void setRequestType(String requestType) {
    this.requestType = requestType;
  }

  /**
   * Epoch timestamp <i>in milliseconds</i> of when event was sent to the API
   **/
  @ApiModelProperty(required = true, value = "Epoch timestamp <i>in milliseconds</i> of when event was sent to the API")
  public Long getSendTimestamp() {
    return sendTimestamp;
  }
  public void setSendTimestamp(Long sendTimestamp) {
    this.sendTimestamp = sendTimestamp;
  }

  /**
   * Unique ID of the new device
   **/
  @ApiModelProperty(required = true, value = "Unique ID of the new device")
  public String getUserId() {
    return userId;
  }
  public void setUserId(String userId) {
    this.userId = userId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DataCollectorUpdateCollectionRequest dataCollectorUpdateCollectionRequest = (DataCollectorUpdateCollectionRequest) o;
    return (this.balance == null ? dataCollectorUpdateCollectionRequest.balance == null : this.balance.equals(dataCollectorUpdateCollectionRequest.balance)) &&
        (this.balanceModification == null ? dataCollectorUpdateCollectionRequest.balanceModification == null : this.balanceModification.equals(dataCollectorUpdateCollectionRequest.balanceModification)) &&
        (this.currency == null ? dataCollectorUpdateCollectionRequest.currency == null : this.currency.equals(dataCollectorUpdateCollectionRequest.currency)) &&
        (this.deviceId == null ? dataCollectorUpdateCollectionRequest.deviceId == null : this.deviceId.equals(dataCollectorUpdateCollectionRequest.deviceId)) &&
        (this.eventProperties == null ? dataCollectorUpdateCollectionRequest.eventProperties == null : this.eventProperties.equals(dataCollectorUpdateCollectionRequest.eventProperties)) &&
        (this.eventTimestamp == null ? dataCollectorUpdateCollectionRequest.eventTimestamp == null : this.eventTimestamp.equals(dataCollectorUpdateCollectionRequest.eventTimestamp)) &&
        (this.name == null ? dataCollectorUpdateCollectionRequest.name == null : this.name.equals(dataCollectorUpdateCollectionRequest.name)) &&
        (this.requestType == null ? dataCollectorUpdateCollectionRequest.requestType == null : this.requestType.equals(dataCollectorUpdateCollectionRequest.requestType)) &&
        (this.sendTimestamp == null ? dataCollectorUpdateCollectionRequest.sendTimestamp == null : this.sendTimestamp.equals(dataCollectorUpdateCollectionRequest.sendTimestamp)) &&
        (this.userId == null ? dataCollectorUpdateCollectionRequest.userId == null : this.userId.equals(dataCollectorUpdateCollectionRequest.userId));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.balance == null ? 0: this.balance.hashCode());
    result = 31 * result + (this.balanceModification == null ? 0: this.balanceModification.hashCode());
    result = 31 * result + (this.currency == null ? 0: this.currency.hashCode());
    result = 31 * result + (this.deviceId == null ? 0: this.deviceId.hashCode());
    result = 31 * result + (this.eventProperties == null ? 0: this.eventProperties.hashCode());
    result = 31 * result + (this.eventTimestamp == null ? 0: this.eventTimestamp.hashCode());
    result = 31 * result + (this.name == null ? 0: this.name.hashCode());
    result = 31 * result + (this.requestType == null ? 0: this.requestType.hashCode());
    result = 31 * result + (this.sendTimestamp == null ? 0: this.sendTimestamp.hashCode());
    result = 31 * result + (this.userId == null ? 0: this.userId.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class DataCollectorUpdateCollectionRequest {\n");
    
    sb.append("  balance: ").append(balance).append("\n");
    sb.append("  balanceModification: ").append(balanceModification).append("\n");
    sb.append("  currency: ").append(currency).append("\n");
    sb.append("  deviceId: ").append(deviceId).append("\n");
    sb.append("  eventProperties: ").append(eventProperties).append("\n");
    sb.append("  eventTimestamp: ").append(eventTimestamp).append("\n");
    sb.append("  name: ").append(name).append("\n");
    sb.append("  requestType: ").append(requestType).append("\n");
    sb.append("  sendTimestamp: ").append(sendTimestamp).append("\n");
    sb.append("  userId: ").append(userId).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
